export const COLORS = {
    primary: '#007AFF',
    secondary: '#5856D6',
    success: '#34C759',
    warning: '#FF9500',
    danger: '#FF3B30',
    info: '#5AC8FA',
    white: '#FFFFFF',
    black: '#000000',
    gray: '#8E8E93',
    lightGray: '#E5E5EA',
    darkGray: '#1C1C1E',
};

export const lightTheme = {
    dark: false,
    colors: {
        background: '#F2F2F7',
        card: '#FFFFFF',
        text: '#000000',
        subText: '#666666',
        border: '#E5E5EA',
        notification: '#FF3B30',
        primary: COLORS.primary,
        success: COLORS.success,
        warning: COLORS.warning,
        danger: COLORS.danger,
        tabBar: '#FFFFFF',
        header: '#FFFFFF',
        input: '#FFFFFF',
        inputBorder: '#E5E5EA',
        chip: '#F0F0F0',
        chipText: '#666666',
    },
};

export const darkTheme = {
    dark: true,
    colors: {
        background: '#121212',
        card: '#1E1E1E',
        text: '#FFFFFF',
        subText: '#AAAAAA',
        border: '#333333',
        notification: '#FF453A',
        primary: '#0A84FF',
        success: '#30D158',
        warning: '#FF9F0A',
        danger: '#FF453A',
        tabBar: '#1E1E1E',
        header: '#1E1E1E',
        input: '#2C2C2E',
        inputBorder: '#333333',
        chip: '#333333',
        chipText: '#FFFFFF',
    },
};
